### PR TITLE
Remove `PriorityList` from Govspeak

### PR DESCRIPTION
**Pull request by MartinJJones**
## What
Remove `PriorityList`, including related tests and documentation.

## Why
Priority List is no longer required as the Primary Links JS module used to render the list on the frontend it to be removed from govuk-publishing-components.

## Visual Changes

| Before | After |
| - | - |
| before | after |

Trello: https://trello.com/c/nezjGrzF/1388-investigate-and-potentially-fix-primary-links-module

### CODE REVIEW

**Review by KludgeKML — APPROVED** [review]
LGTM

**Review by BeckaL — COMMENTED** [review]
Looks good, and always nice to remove code! Small nitpick, could you squash the last two commits that bump the version into one? Would be nice if the bump to 6.9 doesn't appear in the git history since we decided to go with a major bump in the following commit (which absolutely seems the correct call to me 😄 )

**Comment by MartinJJones** [comment]
Thanks @BeckaL, good point!, I've squashed the last 2 commits as recommended 👍

**Review by BeckaL — APPROVED** [review]
Nice, LGTM!

**Review by BeckaL — APPROVED** [review]

**Comment by kevindew** [comment]
I'm a bit worried that prior to merging this we'll need to adapt content of anything that uses this and update guidance. I wrote more on [the components issue](https://github.com/alphagov/govuk_publishing_components/issues/2364)

**Comment by MartinJJones** [comment]
Latest update rebased main to resolve merge conflicts

**Pull request merged**
