### PR TITLE
Incremented Kramdown

### PR DESCRIPTION
**Pull request by jacobtomlinson**
This PR increases the minor version of Kramdown from `1.5.0` to `1.10.0`.

### CODE REVIEW

**Comment by benlovell** [comment]
What's the rationale?

**Comment by jacobtomlinson** [comment]
See the issue which references this PR.

**Comment by benlovell** [comment]
Ah. Gotcha. The build is failing with what seems to be related errors.

**Comment by jacobtomlinson** [comment]
I see, looks like some additional spacing at the end of a `<p>` tag is not being added.

Is this required functionality?

**Comment by jacobtomlinson** [comment]
Any update on this?

**Comment by benlovell** [comment]
@jacobtomlinson Kramdown stripping that whitespace seems reasonable to me. Can you fix up the specs given this new behaviour?

**Comment by jacobtomlinson** [comment]
@benlovell :+1: done

**Comment by matthewford** [comment]
Incase anyone needs to know what changed 
https://github.com/gettalong/kramdown/compare/REL_1_5_0...REL_1_10_0

**Pull request merged**
